# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/print-$PRINT_VERSION-Linux
Summary:        static C++ library for printing
Name:           print-devel
Version:        $PRINT_VERSION
Release:        1
License:        MIT
Group:          print
Vendor:         Humanity















Prefix: /usr





%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS
%define _rpmfilename print-$PRINT_VERSION-Linux.rpm
%define _unpackaged_files_terminate_build 0





%description
print - static C++ library for printing
This library provides simple printing functionality for C++ applications.


# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean








%files
%defattr(-,root,root,-)




%changelog
* Sun May 17 2026 ZaycFerr <aglaya.zayc@mail.ru> 0.1.0.0
- Initial RPM release



