name: CMake Build and Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Download HunterGate
      run: mkdir -p cmake && wget https://raw.githubusercontent.com/cpp-pm/gate/master/cmake/HunterGate.cmake -O cmake/HunterGate.cmake

    - name: Configure CMake
      run: cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build _build

    # Возвращаем запуск тестов через встроенный модуль ctest
    - name: Run Tests
      run: cd _build && ctest --output-on-failure

