name: CMake Build and Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Download HunterGate
      run: mkdir -p cmake && wget https://raw.githubusercontent.com/cpp-pm/gate/master/cmake/HunterGate.cmake -O cmake/HunterGate.cmake

    # Упрощаем конфигурацию, CMake сам увидит тесты внутри проекта
    - name: Configure CMake
      run: cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build _build

    # Запускаем исполняемый файл тестов напрямую из папки сборки
    - name: Run Tests
      run: ./_build/check

