name: Docker Build and Test

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t logger .

    - name: Run Docker Container Test
      run: |
        mkdir -p logs
        echo "Hello from GitHub Actions!" | docker run -i -v "$(pwd)/logs:/home/logs" logger
